### PR TITLE
Added colors to both the parsing and converting (groups and annotation)

### PR DESCRIPTION
**Pull request by thijsgelton**
Added color support for annotation and annotationgroup for ASAP

### CODE REVIEW

**Comment by martvanrijthoven** [comment]
I think this is a nice solution, but I would like to set the color in a Label object, such that we don't have to give the old XML to write_asap_annotations. The AnnotationStructure is already compatible with a Label object, so we just need to create a Label from the parsed label name and label color. I very much like the regex when parsing the color!

**Comment by martvanrijthoven** [comment]
Wait, you already create a Label object with the label name an label color, why do we need the old XML in the write_asap_annotation function?

**Comment by thijsgelton** [comment]
> I like the solution, very much like the regex for parsing the color. But one question, why do we need the old XML in the write_asap_annotation function?

old_xml is use get the AnnotationGroups. Label is for Annotation, but is mostly the color of the groups you want when displaying in ASAP.

**Review by martvanrijthoven — COMMENTED** [review]
You can use something like this:
It first gets all the labels/colors mapping from the AnnotationGroups and then uses that color for the specific label in an annotation. In the wholeslideannotationwriter you can then omit your changes and it should work. The code is not that clean, but the parsers.py should be refactored at some time.


```
def _get_annotation_structures(self, path, labels):
        tree = ET.parse(path)
        opened_annotation = tree.getroot()
        annotation_index = 0
        label_colors = {}
        for parent in opened_annotation:
            if parent.tag == "AnnotationGroups":
                for child in parent:
                    label_colors[child.attrib.get('Name').lower().strip()] = child.attrib.get('Color').lower().strip()
        for parent in opened_annotation:
            for child in parent:
                if child.tag == "Annotation":
                    annotation_type = self._get_annotation_type(child)
                    annotation_color = self._get_annotation_color(child)
                    label_name = self._get_label_name(child, labels)
                    if label_name in label_colors:
                        label_color = label_colors[label_name]
                    else:
                        label_color = '#000000'
                        
                    annotation_label = Label(name=label_name, value=annotation_index,
                                             color=label_color)
                    annotation_coordinates = self._get_coordinates(child)
                    if AsapAnnotationParser.TYPES[annotation_type] == 'polygon' and len(annotation_coordinates) < 3:
                        print('error annotation')
                        continue
                    annotation_holes = self._get_holes(child)
                    if not annotation_label or (
                            not isinstance(annotation_label, Label)
                            and isinstance(labels, Labels)
                            and annotation_label not in labels.names
                    ):
                        continue

                    if (
                            isinstance(annotation_label, Label)
                            and isinstance(labels, Labels)
                            and annotation_label.name not in labels.names
                    ):
                        continue

                    if annotation_type == "pointset":
                        for coordinate in annotation_coordinates:
                            annotation_structure = AnnotationStructure(
                                annotation_path=path,
                                index=annotation_index,
                                type=AsapAnnotationParser.TYPES[annotation_type],
                                label=annotation_label,
                                coordinates=[coordinate],
                                holes=annotation_holes,
                            )
                            annotation_index += 1
                            yield annotation_structure
                        continue

                    annotation_structure = AnnotationStructure(
                        annotation_path=path,
                        index=annotation_index,
                        type=AsapAnnotationParser.TYPES[annotation_type],
                        label=annotation_label,
                        coordinates=annotation_coordinates,
                        holes=annotation_holes,
                    )
                    annotation_index += 1
                    yield annotation_structure
`

**Comment by thijsgelton** [comment]
> You can use something like this: It first gets all the labels/colors mapping from the AnnotationGroups and then uses that color for the specific label in an annotation. In the wholeslideannotationwriter you can then omit your changes and it should work. The code is not that clean, but the parsers.py should be refactored at some time anyway.
> 
> ```
> def _get_annotation_structures(self, path, labels):
>         tree = ET.parse(path)
>         opened_annotation = tree.getroot()
>         annotation_index = 0
>         label_colors = {}
>         for parent in opened_annotation:
>             if parent.tag == "AnnotationGroups":
>                 for child in parent:
>                     label_colors[child.attrib.get('Name').lower().strip()] = child.attrib.get('Color').lower().strip()
>         for parent in opened_annotation:
>             for child in parent:
>                 if child.tag == "Annotation":
>                     annotation_type = self._get_annotation_type(child)
>                     annotation_color = self._get_annotation_color(child)
>                     label_name = self._get_label_name(child, labels)
>                     if label_name in label_colors:
>                         label_color = label_colors[label_name]
>                     else:
>                         label_color = '#000000'
>                         
>                     annotation_label = Label(name=label_name, value=annotation_index,
>                                              color=label_color)
>                     annotation_coordinates = self._get_coordinates(child)
>                     if AsapAnnotationParser.TYPES[annotation_type] == 'polygon' and len(annotation_coordinates) < 3:
>                         print('error annotation')
>                         continue
>                     annotation_holes = self._get_holes(child)
>                     if not annotation_label or (
>                             not isinstance(annotation_label, Label)
>                             and isinstance(labels, Labels)
>                             and annotation_label not in labels.names
>                     ):
>                         continue
> 
>                     if (
>                             isinstance(annotation_label, Label)
>                             and isinstance(labels, Labels)
>                             and annotation_label.name not in labels.names
>                     ):
>                         continue
> 
>                     if annotation_type == "pointset":
>                         for coordinate in annotation_coordinates:
>                             annotation_structure = AnnotationStructure(
>                                 annotation_path=path,
>                                 index=annotation_index,
>                                 type=AsapAnnotationParser.TYPES[annotation_type],
>                                 label=annotation_label,
>                                 coordinates=[coordinate],
>                                 holes=annotation_holes,
>                             )
>                             annotation_index += 1
>                             yield annotation_structure
>                         continue
> 
>                     annotation_structure = AnnotationStructure(
>                         annotation_path=path,
>                         index=annotation_index,
>                         type=AsapAnnotationParser.TYPES[annotation_type],
>                         label=annotation_label,
>                         coordinates=annotation_coordinates,
>                         holes=annotation_holes,
>                     )
>                     annotation_index += 1
>                     yield annotation_structure
> `
> ```

With current changes the XML will be a 1 to 1 conversion of the old one. This way all colours are exactly the same as they were.

**Pull request merged**
